language: java
jdk:
- openjdk8

branches:
  only:
  - master

# Travis CI 서버의 Home
cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
    - yolip51@gmail.com
    - insoo2846@gmail.com

# S3 Deploy
before_deploy:
- zip -r springboot-react *
- mkdir -p deploy
- mv springboot-react.zip deploy/springboot-react.zip
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
  secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
  bucket: springboot-react-deploy # 생성한 S3 버킷
  region: ap-northeast-2
  skip_cleanup: true
  local_dir: deploy # before_deploy에서 생성한 디렉토리
  acl: public_read
  wait-until-deployed: true
  on:
    repo: gongdel-insu/springboot_react #Github 주소
    branch: master

